// apps/compare/src/content/2-templating/6-conditional/vue3/TrafficLight.vue
<script setup>
import { ref, computed } from "vue";
const TRAFFIC_LIGHTS = ["red", "orange", "green"];
const lightIndex = ref(0);

const light = computed(() => TRAFFIC_LIGHTS[lightIndex.value]);

function nextLight() {
	lightIndex.value = (lightIndex.value + 1) % TRAFFIC_LIGHTS.length;
}
</script>

<template>
	<button @click="nextLight">Next light</button>
	<p>Light is: {{ light }}</p>
	<p>
		You must
		<span v-if="light === 'red'">STOP</span>
		<span v-else-if="light === 'orange'">SLOW DOWN</span>
		<span v-else-if="light === 'green'">GO</span>
	</p>
</template>

// apps/compare/src/content/2-templating/6-conditional/svelte5/TrafficLight.svelte
<script>
	const TRAFFIC_LIGHTS = ["red", "orange", "green"];
	let lightIndex = $state(0);

	const light = $derived(TRAFFIC_LIGHTS[lightIndex]);

	function nextLight() {
		lightIndex = (lightIndex + 1) % TRAFFIC_LIGHTS.length;
	}
</script>

<button onclick={nextLight}>Next light</button>
<p>Light is: {light}</p>
<p>
	You must
	{#if light === "red"}
		<span>STOP</span>
	{:else if light === "orange"}
		<span>SLOW DOWN</span>
	{:else if light === "green"}
		<span>GO</span>
	{/if}
</p>
