// apps/compare/src/content/3-lifecycle/2-on-unmount/vue3/Time.vue
<script setup>
import { ref, onUnmounted } from "vue";

const time = ref(new Date().toLocaleTimeString());

const timer = setInterval(() => {
	time.value = new Date().toLocaleTimeString();
}, 1000);

onUnmounted(() => {
	clearInterval(timer);
});
</script>

<template>
	<p>Current time: {{ time }}</p>
</template>

// apps/compare/src/content/3-lifecycle/2-on-unmount/react/Time.jsx
import { useEffect, useState } from "react";

export default function Time() {
	const [time, setTime] = useState(
		new Date().toLocaleTimeString(),
	);

	useEffect(() => {
		const timer = setInterval(() => {
			setTime(new Date().toLocaleTimeString());
		}, 1000);

		return () => {
			clearInterval(timer);
		};
	}, []);

	return <p>Current time: {time}</p>;
}
