// apps/compare/src/content/2-templating/6-conditional/svelte4/TrafficLight.svelte
<script>
	const TRAFFIC_LIGHTS = ["red", "orange", "green"];
	let lightIndex = 0;

	$: light = TRAFFIC_LIGHTS[lightIndex];

	function nextLight() {
		lightIndex =
			(lightIndex + 1) % TRAFFIC_LIGHTS.length;
	}
</script>

<button on:click={nextLight}>Next light</button>
<p>Light is: {light}</p>
<p>
	You must
	{#if light === "red"}
		<span>STOP</span>
	{:else if light === "orange"}
		<span>SLOW DOWN</span>
	{:else if light === "green"}
		<span>GO</span>
	{/if}
</p>

// apps/compare/src/content/2-templating/6-conditional/vue2/TrafficLight.vue
<script>
export default {
	data() {
		return {
			TRAFFIC_LIGHTS: ["red", "orange", "green"],
			lightIndex: 0,
		};
	},
	computed: {
		light() {
			return this.TRAFFIC_LIGHTS[this.lightIndex];
		},
	},
	methods: {
		nextLight() {
			this.lightIndex =
				(this.lightIndex + 1) %
				this.TRAFFIC_LIGHTS.length;
		},
	},
};
</script>

<template>
	<div>
		<button @click="nextLight">Next light</button>
		<p>Light is: {{ light }}</p>
		<p>
			You must
			<span v-if="light === 'red'">STOP</span>
			<span v-else-if="light === 'orange'"
				>SLOW DOWN</span
			>
			<span v-else-if="light === 'green'">GO</span>
		</p>
	</div>
</template>
