// apps/compare/src/content/4-component-composition/2-emit-to-parent/react/App.jsx
import { useState } from "react";
import AnswerButton from "./AnswerButton.jsx";

export default function App() {
	const [isHappy, setIsHappy] = useState(true);

	function onAnswerNo() {
		setIsHappy(false);
	}

	function onAnswerYes() {
		setIsHappy(true);
	}

	return (
		<>
			<p>Are you happy?</p>
			<AnswerButton
				onYes={onAnswerYes}
				onNo={onAnswerNo}
			/>
			<p style={{ fontSize: 50 }}>
				{isHappy ? "😀" : "😥"}
			</p>
		</>
	);
}

// apps/compare/src/content/4-component-composition/2-emit-to-parent/qwik/App.tsx
import { $, component$, useStore } from "@builder.io/qwik";
import AnswerButton from "./AnswerButton";

const App = component$(() => {
	const store = useStore({
		isHappy: true,
	});

	const onAnswerNo = $(() => {
		store.isHappy = false;
	});

	const onAnswerYes = $(() => {
		store.isHappy = true;
	});

	return (
		<>
			<p>Are you happy?</p>
			<AnswerButton onYes$={onAnswerYes} onNo$={onAnswerNo} />
			<p style={{ fontSize: 50 }}>
				{store.isHappy ? "ðŸ˜€" : "ðŸ˜¥"}
			</p>
		</>
	);
});

export default App;
