// apps/compare/src/content/4-component-composition/5-context/vue2/App.vue
<script>
import UserProfile from "./UserProfile.vue";

export default {
	components: { UserProfile },
	provide() {
		return {
			user: Object.assign(this.user, {
				updateUsername: this.updateUsername,
			}),
		};
	},
	data() {
		return {
			user: {
				id: 1,
				username: "unicorn42",
				email: "unicorn42@example.com",
			},
		};
	},
	methods: {
		updateUsername(newUsername) {
			this.user.username = newUsername;
		},
	},
};
</script>

<template>
	<div>
		<h1>Welcome back, {{ user.username }}</h1>
		<UserProfile />
	</div>
</template>

// apps/compare/src/content/4-component-composition/5-context/qwik/App.tsx
import {
	$,
	component$,
	createContext,
	useContextProvider,
	useStore,
} from "@builder.io/qwik";
import UserProfile from "./UserProfile";

export const UserContext = createContext("user-context");

const App = component$(() => {
	const user = useStore({
		id: 1,
		username: "unicorn42",
		email: "unicorn42@example.com",
	});

	const updateUsername = $((newUsername) => {
		user.username = newUsername;
	});

	useContextProvider(UserContext, {
		user,
		updateUsername,
	});

	return (
		<>
			<h1>Welcome back, {user.username}</h1>
			<UserProfile />
		</>
	);
});

export default App;
