// apps/compare/src/content/2-templating/6-conditional/react/TrafficLight.jsx
import { useState } from "react";

const TRAFFIC_LIGHTS = ["red", "orange", "green"];

export default function TrafficLight() {
	const [lightIndex, setLightIndex] = useState(0);

	const light = TRAFFIC_LIGHTS[lightIndex];

	function nextLight() {
		setLightIndex((lightIndex + 1) % TRAFFIC_LIGHTS.length);
	}

	return (
		<>
			<button onClick={nextLight}>Next light</button>
			<p>Light is: {light}</p>
			<p>
				You must
				{light === "red" && <span>STOP</span>}
				{light === "orange" && <span>SLOW DOWN</span>}
				{light === "green" && <span>GO</span>}
			</p>
		</>
	);
}

// apps/compare/src/content/2-templating/6-conditional/svelte4/TrafficLight.svelte
<script>
	const TRAFFIC_LIGHTS = ["red", "orange", "green"];
	let lightIndex = 0;

	$: light = TRAFFIC_LIGHTS[lightIndex];

	function nextLight() {
		lightIndex =
			(lightIndex + 1) % TRAFFIC_LIGHTS.length;
	}
</script>

<button on:click={nextLight}>Next light</button>
<p>Light is: {light}</p>
<p>
	You must
	{#if light === "red"}
		<span>STOP</span>
	{:else if light === "orange"}
		<span>SLOW DOWN</span>
	{:else if light === "green"}
		<span>GO</span>
	{/if}
</p>
