// apps/compare/src/content/3-lifecycle/2-on-unmount/react/Time.jsx
import { useEffect, useState } from "react";

export default function Time() {
	const [time, setTime] = useState(
		new Date().toLocaleTimeString(),
	);

	useEffect(() => {
		const timer = setInterval(() => {
			setTime(new Date().toLocaleTimeString());
		}, 1000);

		return () => {
			clearInterval(timer);
		};
	}, []);

	return <p>Current time: {time}</p>;
}

// apps/compare/src/content/3-lifecycle/2-on-unmount/vue2/Time.vue
<script>
export default {
	data() {
		return {
			time: new Date().toLocaleTimeString(),
			timer: null,
		};
	},
	mounted() {
		this.timer = setInterval(() => {
			this.time = new Date().toLocaleTimeString();
		}, 1000);
	},
	beforeUnmount() {
		clearInterval(this.timer);
	},
};
</script>

<template>
	<p>Current time: {{ time }}</p>
</template>
