// apps/compare/src/content/4-component-composition/5-context/svelte4/UserProfile.svelte
<script>
	import { getContext } from "svelte";

	const userStore = getContext("user");
</script>

<div>
	<h2>My Profile</h2>
	<p>Username: {$userStore.username}</p>
	<p>Email: {$userStore.email}</p>
	<button on:click={() => userStore.updateUsername("Jane")}>
		Update username to Jane
	</button>
</div>

// apps/compare/src/content/4-component-composition/5-context/vue3/UserProfile.vue
<script setup>
import { inject } from "vue";
const { user, updateUsername } = inject("user");
</script>

<template>
	<div>
		<h2>My Profile</h2>
		<p>Username: {{ user.username }}</p>
		<p>Email: {{ user.email }}</p>
		<button @click="() => updateUsername('Jane')">
			Update username to Jane
		</button>
	</div>
</template>
