// apps/compare/src/content/4-component-composition/2-emit-to-parent/svelte4/App.svelte
<script>
	import AnswerButton from "./AnswerButton.svelte";

	let isHappy = true;

	function onAnswerNo() {
		isHappy = false;
	}

	function onAnswerYes() {
		isHappy = true;
	}
</script>

<p>Are you happy?</p>
<AnswerButton on:yes={onAnswerYes} on:no={onAnswerNo} />
<p style="font-size: 50px;">{isHappy ? "😀" : "😥"}</p>

// apps/compare/src/content/4-component-composition/2-emit-to-parent/vue3/App.vue
<script setup>
import { ref } from "vue";
import AnswerButton from "./AnswerButton.vue";

let isHappy = ref(true);

function onAnswerNo() {
	isHappy.value = false;
}

function onAnswerYes() {
	isHappy.value = true;
}
</script>

<template>
	<p>Are you happy?</p>
	<AnswerButton @yes="onAnswerYes" @no="onAnswerNo" />
	<p style="font-size: 50px">
		{{ isHappy ? "😀" : "😥" }}
	</p>
</template>
