// apps/compare/src/content/7-webapp-features/2-fetch-data/qwik/App.tsx
import { component$, Resource, useResource$ } from "@builder.io/qwik";

type UsersResponse = {
	results: {
		picture: {
			thumbnail: string;
		};
		name: {
			first: string;
			last: string;
		};
	}[];
};

export async function fetchUsers() {
	return (
		await fetch("https://randomuser.me/api/?results=3")
	).json();
}

export const App = component$(() => {
	const data = useResource$<UsersResponse>(fetchUsers);

	return (
		<Resource
			value={data}
			onPending={() => <p>Fetching users...</p>}
			onRejected={() => (
				<p>An error occurred while fetching users</p>
			)}
			onResolved={({ results: users }) => (
				<ul>
					{users.map((user) => (
						<li>
							<img
								src={user.picture.thumbnail}
								alt="user"
							/>
							<p>
								{user.name.first} {user.name.last}
							</p>
						</li>
					))}
				</ul>
			)}
		/>
	);
});

// apps/compare/src/content/7-webapp-features/2-fetch-data/solid/App.jsx
import {
	createResource,
	For,
	Match,
	Switch,
} from "solid-js";

async function fetchUsers() {
	return (
		await fetch("https://randomuser.me/api/?results=3")
	).json();
}

export default function App() {
	const [data] = createResource(fetchUsers);
	const users = () => data()?.results;

	return (
		<Switch>
			<Match when={data.loading}>
				<p>Fetching users...</p>
			</Match>
			<Match when={data.error}>
				<p>
					An error occurred while fetching users
				</p>
			</Match>
			<Match when={users()}>
				<ul>
					<For each={users()}>
						{(user) => (
							<li>
								<img
									src={
										user.picture
											.thumbnail
									}
									alt="user"
								/>
								<p>
									{user.name.first}{" "}
									{user.name.last}
								</p>
							</li>
						)}
					</For>
				</ul>
			</Match>
		</Switch>
	);
}
