// apps/compare/src/content/4-component-composition/2-emit-to-parent/vue2/App.vue
<script>
import AnswerButton from "./AnswerButton.vue";
export default {
	components: {
		AnswerButton,
	},
	data() {
		return {
			isHappy: true,
		};
	},
	methods: {
		onAnswerNo() {
			this.isHappy = false;
		},
		onAnswerYes() {
			this.isHappy = true;
		},
	},
};
</script>

<template>
	<div>
		<p>Are you happy?</p>
		<AnswerButton @yes="onAnswerYes" @no="onAnswerNo" />
		<p style="font-size: 50px">
			{{ isHappy ? "😀" : "😥" }}
		</p>
	</div>
</template>

// apps/compare/src/content/4-component-composition/2-emit-to-parent/svelte4/App.svelte
<script>
	import AnswerButton from "./AnswerButton.svelte";

	let isHappy = true;

	function onAnswerNo() {
		isHappy = false;
	}

	function onAnswerYes() {
		isHappy = true;
	}
</script>

<p>Are you happy?</p>
<AnswerButton on:yes={onAnswerYes} on:no={onAnswerNo} />
<p style="font-size: 50px;">{isHappy ? "😀" : "😥"}</p>
