// apps/compare/src/content/6-form-input/4-select/qwik/ColorSelect.tsx
import { component$, useSignal } from "@builder.io/qwik";

export const colors = [
	{ id: 1, text: "red" },
	{ id: 2, text: "blue" },
	{ id: 3, text: "green" },
	{
		id: 4,
		text: "gray",
		isDisabled: true,
	},
];

const ColorSelect = component$(() => {
	const selectedColorId = useSignal("2");

	return (
		<select bind:value={selectedColorId}>
			{colors.map((color) => (
				<option
					key={color.id}
					value={color.id}
					disabled={color.isDisabled}
					selected={
						`${color.id}` === selectedColorId.value
					}>
					{color.text}
				</option>
			))}
		</select>
	);
});

export default ColorSelect;

// apps/compare/src/content/6-form-input/4-select/svelte4/ColorSelect.svelte
<script>
	let selectedColorId = 2;

	const colors = [
		{ id: 1, text: "red" },
		{ id: 2, text: "blue" },
		{ id: 3, text: "green" },
		{ id: 4, text: "gray", isDisabled: true },
	];
</script>

<select bind:value={selectedColorId}>
	{#each colors as color}
		<option
			value={color.id}
			disabled={color.isDisabled}>
			{color.text}
		</option>
	{/each}
</select>
