// apps/compare/src/content/6-form-input/2-checkbox/lit/is-available.js
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("is-available")
export class IsAvailable extends LitElement {
	@state()
	isAvailable = false;

	handleChange() {
		this.isAvailable = !this.isAvailable;
	}

	render() {
		return html`
			<input
				id="is-available"
				type="checkbox"
				?checked=${this.isAvailable}
				@change=${this.handleChange} />
			<label for="is-available">Is available</label>
		`;
	}
}

// apps/compare/src/content/6-form-input/2-checkbox/react/IsAvailable.jsx
import { useState } from "react";

export default function IsAvailable() {
	const [isAvailable, setIsAvailable] = useState(false);

	function handleChange() {
		setIsAvailable(!isAvailable);
	}

	return (
		<>
			<input
				id="is-available"
				type="checkbox"
				checked={isAvailable}
				onChange={handleChange}
			/>
			<label htmlFor="is-available">Is available</label>
		</>
	);
}
