// apps/compare/src/content/6-form-input/1-input-text/solid/InputHello.jsx
import { createSignal } from "solid-js";

export default function InputHello() {
	const [text, setText] = createSignal("Hello world");

	function handleChange(event) {
		setText(event.target.value);
	}

	return (
		<>
			<p>{text()}</p>
			<input value={text()} onInput={handleChange} />
		</>
	);
}

// apps/compare/src/content/6-form-input/1-input-text/lit/input-hello.js
import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";

@customElement("input-hello")
export class InputHello extends LitElement {
	@state()
	text = "Hello World";

	handleInput(event) {
		this.text = event.target.value;
	}

	render() {
		return html`
			<p>${this.text}</p>
			<input
				value=${this.text}
				@input=${this.handleInput} />
		`;
	}
}
