// apps/compare/src/content/6-form-input/3-radio/qwik/PickPill.tsx
import { component$, useSignal } from "@builder.io/qwik";

const PickPill = component$(() => {
	const pickedColor = useSignal("red");

	return (
		<>
			<div>Picked: {pickedColor.value}</div>
			<input
				id="blue-pill"
				type="radio"
				bind:value={pickedColor}
				checked={pickedColor.value === "blue"}
				value="blue"
			/>
			<label for="blue-pill">Blue pill</label>

			<input
				id="red-pill"
				type="radio"
				checked={pickedColor.value === "red"}
				bind:value={pickedColor}
				value="red"
			/>
			<label for="red-pill">Red pill</label>
		</>
	);
});

export default PickPill;

// apps/compare/src/content/6-form-input/3-radio/svelte5/PickPill.svelte
<script>
	let picked = $state("red");
</script>

<div>Picked: {picked}</div>

<input
	id="blue-pill"
	bind:group={picked}
	type="radio"
	value="blue" />
<label for="blue-pill">Blue pill</label>

<input
	id="red-pill"
	bind:group={picked}
	type="radio"
	value="red" />
<label for="red-pill">Red pill</label>
