// apps/compare/src/content/6-form-input/2-checkbox/react/IsAvailable.jsx
import { useState } from "react";

export default function IsAvailable() {
	const [isAvailable, setIsAvailable] = useState(false);

	function handleChange() {
		setIsAvailable(!isAvailable);
	}

	return (
		<>
			<input
				id="is-available"
				type="checkbox"
				checked={isAvailable}
				onChange={handleChange}
			/>
			<label htmlFor="is-available">Is available</label>
		</>
	);
}

// apps/compare/src/content/6-form-input/2-checkbox/qwik/IsAvailable.tsx
import { component$, useSignal } from "@builder.io/qwik";

const IsAvailable = component$(() => {
	const isAvailable = useSignal(false);

	return (
		<>
			<input
				id="is-available"
				type="checkbox"
				bind:checked={isAvailable}
			/>
			<label for="is-available">Is available</label>
		</>
	);
});

export default IsAvailable;
