// apps/compare/src/content/4-component-composition/2-emit-to-parent/solid/App.jsx
import { createSignal } from "solid-js";
import AnswerButton from "./AnswerButton.jsx";

export default function App() {
	const [isHappy, setIsHappy] = createSignal(true);

	function onAnswerNo() {
		setIsHappy(false);
	}

	function onAnswerYes() {
		setIsHappy(true);
	}

	return (
		<>
			<p>Are you happy?</p>
			<AnswerButton
				onYes={onAnswerYes}
				onNo={onAnswerNo}
			/>
			<p style={{ "font-size": "50px" }}>
				{isHappy() ? "😀" : "😥"}
			</p>
		</>
	);
}

// apps/compare/src/content/4-component-composition/2-emit-to-parent/react/App.jsx
import { useState } from "react";
import AnswerButton from "./AnswerButton.jsx";

export default function App() {
	const [isHappy, setIsHappy] = useState(true);

	function onAnswerNo() {
		setIsHappy(false);
	}

	function onAnswerYes() {
		setIsHappy(true);
	}

	return (
		<>
			<p>Are you happy?</p>
			<AnswerButton
				onYes={onAnswerYes}
				onNo={onAnswerNo}
			/>
			<p style={{ fontSize: 50 }}>
				{isHappy ? "😀" : "😥"}
			</p>
		</>
	);
}
