// apps/compare/src/content/4-component-composition/5-context/react/App.jsx
import { createContext, useState } from "react";
import UserProfile from "./UserProfile";

export const UserContext = createContext();

export default function App() {
	// In a real app, you would fetch the user data from an API
	const [user, setUser] = useState({
		id: 1,
		username: "unicorn42",
		email: "unicorn42@example.com",
	});

	function updateUsername(newUsername) {
		setUser((userData) => ({
			...userData,
			username: newUsername,
		}));
	}

	return (
		<>
			<h1>Welcome back, {user.username}</h1>
			<UserContext.Provider
				value={{
					...user,
					updateUsername,
				}}>
				<UserProfile />
			</UserContext.Provider>
		</>
	);
}

// apps/compare/src/content/4-component-composition/5-context/svelte4/App.svelte
<script>
	import { setContext } from "svelte";
	import UserProfile from "./UserProfile.svelte";
	import createUserStore from "./createUserStore.js";

	// In a real app, you would fetch the user data from an API
	const userStore = createUserStore({
		id: 1,
		username: "unicorn42",
		email: "unicorn42@example.com",
	});

	setContext("user", userStore);
</script>

<h1>Welcome back, {$userStore.username}</h1>
<UserProfile />
